print ('#SUMA 2 + 2 = ' , (2 + 2)) 
print ('#RESTA 2 - 2 = ' , (2 - 2)) 
print ('#MULTIPLICACION 2 * 2 = ' , (2 * 2)) 
print ('#DIVISION 10 / 9 = ' , (10 / 9)) 
print ('#RESIDUO 10 % 9, Toma el residual, o resto por repartir :) = ' , (10 % 9)) 
print ('#ENTERO 10 // 9, Toma el entero = ' , (10 // 9)) 
print ('#POTENCIA 2 ** 3  = ' , (2 ** 3)) 
print ('\n') 
print ('#OPERACIONES') 
print ('2 ** 3 + 3 - 7 / 1 // 4  = ' , (2 ** 3 + 3 - 7 / 1 // 4)) 

print ('\n') 
print ('#Python da la sgte prioridad  de Izq a derecha para resolver operaciones aritmeticas')
print ("P arentesis ()")
print ("E xponenciación **")
print ("M últiplicación *")
print ("D ivisión / [Solo valor entero // , modulo %)")
print ("A dición +")
print ("S sustracción -")